### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by daniel-de-wit** [czim/laravel-cms-models#40]
PHP 7.2 changed `count()` to throw an `E_WARNING` when attempting to count non-countable types (this includes the sizeof() alias function).

[PHP RFC: Counting of non-countable objects](https://wiki.php.net/rfc/counting_non_countables)

[Migrating from PHP 7.1.x to PHP 7.2.x](http://php.net/manual/en/migration72.incompatible.php)

I suggest adding some sort of helper function to check if a variable contains a countable object before
counting it, something like this:

```php
function is_countable ($value) {
    return is_array($value) || $value instanceof Countable;
}
```

Where should this function be placed?

**Comment by czim** [comment]
Count is used a *lot* in this project, but upon quick examination I have not found an instance where it should not warn when its subject is not countable.

I think it is definitely warranted to get warnings when someone misconfigures (or mis-extends) model configurations or controllers to provide scalars rather than arrays or Collections to views, for instance.

Do you have a ready example where such a check would be warranted?
If it is to be used enough times, and the Laravel framework wouldn't provide a helper for us, I'd not be opposed to inlude it in the helpers file of the cms-core package.
